import { defineConfig } from 'tsup';

export default defineConfig([
  {
    name: 'fetchff',
    globalName: 'fetchff',
    entry: ['src/index.ts'],
    format: ['esm', 'iife'],
    target: 'es2018',
    dts: true,
    clean: true,
    outDir: 'dist/browser',
    sourcemap: true,
    minify: true,
    treeshake: true,
    splitting: false,
  },
  {
    name: 'fetchff-node',
    globalName: 'fetchff',
    entry: ['src/index.ts'],
    format: ['cjs'],
    target: 'node18',
    outDir: 'dist/node',
    sourcemap: true,
    minify: true,
    treeshake: true,
    dts: false, // Types already generated by browser build
    clean: false,
  },
  {
    name: 'fetchff-react',
    globalName: 'fetchffReact',
    entry: ['src/react/index.ts'],
    target: 'es2018',
    dts: { entry: 'src/react/index.ts' },
    format: ['esm', 'cjs'],
    outDir: 'dist/react',
    sourcemap: true,
    clean: false,
    minify: true,
    treeshake: true,
    bundle: true,
    splitting: false,
    external: [
      'react',
      'react-dom',
      'fetchff',
      '../index',
      '../config-handler',
    ], // prevent bundling React
  },
]);
